---
driver:
  name: vagrant
driver_config:
  customize:
    audio: "none"

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false

platforms:
  - name: centos/7

verifier:
  name: serverspec

suites:
  - name: default
    provisioner:
      data_path: "."
      name: ansible_playbook
      playbook: playbooks/deploy.yml
      additional_copy_path:
        - "."
        - "./tests"
    verifier:
      patterns:
        - tests/test_spec.rb
