---
- hosts: localhost
#  connection: local

#  vars
#    telegram_bot_token: ""
#    telegram_chat_id: ""
#    target_web_page: ""
#    prove_string: ""

  pre_tasks:
    - name: Check the OS compatibility
      fail:
        msg: "Target OS version is incompatible with this scenario"
      when: 
        - (ansible_distribution != "Debian" and ansible_distribution_major_version != "9") 
        - (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")
      tags: check

  roles:
    - docker-engine-install

  post_tasks:
    - name: "Run the alerter container"
      docker_container:
        name: alerter
        state: started
        pull: yes
        restart: yes
        recreate: yes
        restart_policy: "unless-stopped"
        image: "anmcarrow/alerter"
#          env:
#            TOKEN="{{ telegram_bot_token }}"
#            CHATID="{{ telegram_chat_id }}"
#            URL="{{ target_web_page }}"
#            PROVESTRING="{{ prove_string }}"
      tags: run

